export const mockProducts = [
  {
    "id": 1,
    "name": "Wireless Headphones",
    "description": "Premium noise-cancelling wireless headphones with 30-hour battery life",
    "price": 199.99,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=300&h=300&fit=crop",
    "stock": 15,
    "rating": 4.5,
    "reviews": 128
  },
  {
    "id": 2,
    "name": "Smart Watch",
    "description": "Advanced fitness tracking and health monitoring smartwatch",
    "price": 299.99,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=300&h=300&fit=crop",
    "stock": 8,
    "rating": 4.3,
    "reviews": 95
  },
  {
    "id": 3,
    "name": "Portable Charger",
    "description": "Fast-charging 20000mAh portable battery for all devices",
    "price": 49.99,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1609594040430-3b9b92d0a0d3?w=300&h=300&fit=crop",
    "stock": 25,
    "rating": 4.6,
    "reviews": 256
  },
  {
    "id": 4,
    "name": "USB-C Cable 2m",
    "description": "Durable USB-C cable with fast charging support",
    "price": 14.99,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&h=300&fit=crop",
    "stock": 50,
    "rating": 4.4,
    "reviews": 180
  },
  {
    "id": 5,
    "name": "Laptop Stand",
    "description": "Adjustable aluminum laptop stand for better ergonomics",
    "price": 39.99,
    "category": "Office",
    "image": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=300&h=300&fit=crop",
    "stock": 12,
    "rating": 4.7,
    "reviews": 203
  },
  {
    "id": 6,
    "name": "Mechanical Keyboard",
    "description": "RGB backlit mechanical keyboard with customizable keys",
    "price": 129.99,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=300&h=300&fit=crop",
    "stock": 20,
    "rating": 4.8,
    "reviews": 342
  },
  {
    "id": 7,
    "name": "Wireless Mouse",
    "description": "Precision wireless mouse with ergonomic design",
    "price": 34.99,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-1527814050087-3793815479db?w=300&h=300&fit=crop",
    "stock": 30,
    "rating": 4.5,
    "reviews": 167
  },
  {
    "id": 8,
    "name": "Monitor Light Bar",
    "description": "Auto-dimming monitor light bar to reduce eye strain",
    "price": 79.99,
    "category": "Office",
    "image": "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=300&h=300&fit=crop",
    "stock": 10,
    "rating": 4.6,
    "reviews": 89
  },
  {
    "id": 9,
    "name": "Smart Watch",
    "description": "High-quality smart watch with excellent features and performance",
    "price": 48,
    "category": "Sports",
    "image": "https://images.unsplash.com/photo-107050841177?w=300&h=300&fit=crop",
    "stock": 11,
    "rating": 4.7,
    "reviews": 275
  },
  {
    "id": 10,
    "name": "Premium Speaker",
    "description": "High-quality premium speaker with excellent features and performance",
    "price": 204,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-787443434411?w=300&h=300&fit=crop",
    "stock": 42,
    "rating": 3.3,
    "reviews": 124
  },
  {
    "id": 11,
    "name": "Professional Bag",
    "description": "High-quality professional bag with excellent features and performance",
    "price": 203,
    "category": "Books",
    "image": "https://images.unsplash.com/photo-421903695051?w=300&h=300&fit=crop",
    "stock": 11,
    "rating": 3.7,
    "reviews": 428
  },
  {
    "id": 12,
    "name": "Durable Desk",
    "description": "High-quality durable desk with excellent features and performance",
    "price": 147,
    "category": "Books",
    "image": "https://images.unsplash.com/photo-439787338408?w=300&h=300&fit=crop",
    "stock": 2,
    "rating": 4.2,
    "reviews": 27
  },
  {
    "id": 13,
    "name": "Compact Speaker",
    "description": "High-quality compact speaker with excellent features and performance",
    "price": 431,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-592110438331?w=300&h=300&fit=crop",
    "stock": 22,
    "rating": 4.9,
    "reviews": 256
  },
  {
    "id": 14,
    "name": "Professional Mouse",
    "description": "High-quality professional mouse with excellent features and performance",
    "price": 426,
    "category": "Office",
    "image": "https://images.unsplash.com/photo-248747311293?w=300&h=300&fit=crop",
    "stock": 29,
    "rating": 3.6,
    "reviews": 270
  },
  {
    "id": 15,
    "name": "Durable Shoes",
    "description": "High-quality durable shoes with excellent features and performance",
    "price": 412,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-951558718111?w=300&h=300&fit=crop",
    "stock": 40,
    "rating": 4.9,
    "reviews": 248
  },
  {
    "id": 16,
    "name": "High-Quality Printer",
    "description": "High-quality high-quality printer with excellent features and performance",
    "price": 112,
    "category": "Office",
    "image": "https://images.unsplash.com/photo-410390618721?w=300&h=300&fit=crop",
    "stock": 39,
    "rating": 3.8,
    "reviews": 439
  },
  {
    "id": 17,
    "name": "High-Quality Charger",
    "description": "High-quality high-quality charger with excellent features and performance",
    "price": 244,
    "category": "Books",
    "image": "https://images.unsplash.com/photo-999830154855?w=300&h=300&fit=crop",
    "stock": 48,
    "rating": 4.4,
    "reviews": 149
  },
  {
    "id": 18,
    "name": "Durable Laptop",
    "description": "High-quality durable laptop with excellent features and performance",
    "price": 276,
    "category": "Clothing",
    "image": "https://images.unsplash.com/photo-360821606486?w=300&h=300&fit=crop",
    "stock": 31,
    "rating": 4.7,
    "reviews": 101
  },
  {
    "id": 19,
    "name": "Ergonomic Cable",
    "description": "High-quality ergonomic cable with excellent features and performance",
    "price": 264,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-851864864087?w=300&h=300&fit=crop",
    "stock": 24,
    "rating": 3.8,
    "reviews": 224
  },
  {
    "id": 20,
    "name": "Compact Printer",
    "description": "High-quality compact printer with excellent features and performance",
    "price": 108,
    "category": "Clothing",
    "image": "https://images.unsplash.com/photo-716590561454?w=300&h=300&fit=crop",
    "stock": 1,
    "rating": 4.3,
    "reviews": 245
  },
  {
    "id": 21,
    "name": "Ergonomic Charger",
    "description": "High-quality ergonomic charger with excellent features and performance",
    "price": 112,
    "category": "Office",
    "image": "https://images.unsplash.com/photo-394384030699?w=300&h=300&fit=crop",
    "stock": 50,
    "rating": 3.3,
    "reviews": 70
  },
  {
    "id": 22,
    "name": "Durable Laptop",
    "description": "High-quality durable laptop with excellent features and performance",
    "price": 203,
    "category": "Home",
    "image": "https://images.unsplash.com/photo-750884862199?w=300&h=300&fit=crop",
    "stock": 39,
    "rating": 3.7,
    "reviews": 185
  },
  {
    "id": 23,
    "name": "High-Quality Glasses",
    "description": "High-quality high-quality glasses with excellent features and performance",
    "price": 127,
    "category": "Sports",
    "image": "https://images.unsplash.com/photo-722045663452?w=300&h=300&fit=crop",
    "stock": 41,
    "rating": 4.1,
    "reviews": 146
  },
  {
    "id": 24,
    "name": "Durable Mouse",
    "description": "High-quality durable mouse with excellent features and performance",
    "price": 466,
    "category": "Clothing",
    "image": "https://images.unsplash.com/photo-4153870234?w=300&h=300&fit=crop",
    "stock": 41,
    "rating": 4.3,
    "reviews": 249
  },
  {
    "id": 25,
    "name": "High-Quality Headphones",
    "description": "High-quality high-quality headphones with excellent features and performance",
    "price": 417,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-112392415640?w=300&h=300&fit=crop",
    "stock": 15,
    "rating": 3.1,
    "reviews": 193
  },
  {
    "id": 26,
    "name": "Compact Camera",
    "description": "High-quality compact camera with excellent features and performance",
    "price": 366,
    "category": "Books",
    "image": "https://images.unsplash.com/photo-509805748479?w=300&h=300&fit=crop",
    "stock": 29,
    "rating": 3.3,
    "reviews": 478
  },
  {
    "id": 27,
    "name": "Durable Bag",
    "description": "High-quality durable bag with excellent features and performance",
    "price": 31,
    "category": "Sports",
    "image": "https://images.unsplash.com/photo-911159692805?w=300&h=300&fit=crop",
    "stock": 21,
    "rating": 4.7,
    "reviews": 144
  },
  {
    "id": 28,
    "name": "Portable Camera",
    "description": "High-quality portable camera with excellent features and performance",
    "price": 471,
    "category": "Office",
    "image": "https://images.unsplash.com/photo-988062293228?w=300&h=300&fit=crop",
    "stock": 45,
    "rating": 3.1,
    "reviews": 70
  },
  {
    "id": 29,
    "name": "Wireless Shoes",
    "description": "High-quality wireless shoes with excellent features and performance",
    "price": 474,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-212989710737?w=300&h=300&fit=crop",
    "stock": 36,
    "rating": 3.6,
    "reviews": 425
  },
  {
    "id": 30,
    "name": "Smart Monitor",
    "description": "High-quality smart monitor with excellent features and performance",
    "price": 156,
    "category": "Books",
    "image": "https://images.unsplash.com/photo-679081245708?w=300&h=300&fit=crop",
    "stock": 47,
    "rating": 3.9,
    "reviews": 186
  },
  {
    "id": 31,
    "name": "Professional Tablet",
    "description": "High-quality professional tablet with excellent features and performance",
    "price": 407,
    "category": "Office",
    "image": "https://images.unsplash.com/photo-259013389385?w=300&h=300&fit=crop",
    "stock": 33,
    "rating": 3.3,
    "reviews": 60
  },
  {
    "id": 32,
    "name": "Advanced Keyboard",
    "description": "High-quality advanced keyboard with excellent features and performance",
    "price": 53,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-785360094927?w=300&h=300&fit=crop",
    "stock": 38,
    "rating": 4.3,
    "reviews": 38
  },
  {
    "id": 33,
    "name": "Wireless Stand",
    "description": "High-quality wireless stand with excellent features and performance",
    "price": 245,
    "category": "Home",
    "image": "https://images.unsplash.com/photo-780817247694?w=300&h=300&fit=crop",
    "stock": 11,
    "rating": 3.3,
    "reviews": 172
  },
  {
    "id": 34,
    "name": "Portable Desk",
    "description": "High-quality portable desk with excellent features and performance",
    "price": 383,
    "category": "Office",
    "image": "https://images.unsplash.com/photo-972158802156?w=300&h=300&fit=crop",
    "stock": 20,
    "rating": 4.7,
    "reviews": 496
  },
  {
    "id": 35,
    "name": "Premium Charger",
    "description": "High-quality premium charger with excellent features and performance",
    "price": 234,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-693306222792?w=300&h=300&fit=crop",
    "stock": 38,
    "rating": 4.2,
    "reviews": 304
  },
  {
    "id": 36,
    "name": "Premium Camera",
    "description": "High-quality premium camera with excellent features and performance",
    "price": 183,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-272777811690?w=300&h=300&fit=crop",
    "stock": 20,
    "rating": 4.9,
    "reviews": 326
  },
  {
    "id": 37,
    "name": "Professional Printer",
    "description": "High-quality professional printer with excellent features and performance",
    "price": 449,
    "category": "Home",
    "image": "https://images.unsplash.com/photo-366462085919?w=300&h=300&fit=crop",
    "stock": 33,
    "rating": 3.1,
    "reviews": 480
  },
  {
    "id": 38,
    "name": "High-Quality Bag",
    "description": "High-quality high-quality bag with excellent features and performance",
    "price": 30,
    "category": "Clothing",
    "image": "https://images.unsplash.com/photo-514542375032?w=300&h=300&fit=crop",
    "stock": 5,
    "rating": 5,
    "reviews": 393
  },
  {
    "id": 39,
    "name": "Premium Laptop",
    "description": "High-quality premium laptop with excellent features and performance",
    "price": 283,
    "category": "Clothing",
    "image": "https://images.unsplash.com/photo-543322539455?w=300&h=300&fit=crop",
    "stock": 19,
    "rating": 3.3,
    "reviews": 350
  },
  {
    "id": 40,
    "name": "Advanced Stand",
    "description": "High-quality advanced stand with excellent features and performance",
    "price": 28,
    "category": "Books",
    "image": "https://images.unsplash.com/photo-610485221453?w=300&h=300&fit=crop",
    "stock": 47,
    "rating": 4.9,
    "reviews": 261
  },
  {
    "id": 41,
    "name": "Premium Tablet",
    "description": "High-quality premium tablet with excellent features and performance",
    "price": 415,
    "category": "Books",
    "image": "https://images.unsplash.com/photo-181718274659?w=300&h=300&fit=crop",
    "stock": 42,
    "rating": 3.8,
    "reviews": 245
  },
  {
    "id": 42,
    "name": "Smart Tablet",
    "description": "High-quality smart tablet with excellent features and performance",
    "price": 479,
    "category": "Books",
    "image": "https://images.unsplash.com/photo-243687927039?w=300&h=300&fit=crop",
    "stock": 12,
    "rating": 3.1,
    "reviews": 147
  },
  {
    "id": 43,
    "name": "Ergonomic Headphones",
    "description": "High-quality ergonomic headphones with excellent features and performance",
    "price": 485,
    "category": "Books",
    "image": "https://images.unsplash.com/photo-694756620181?w=300&h=300&fit=crop",
    "stock": 13,
    "rating": 4.2,
    "reviews": 460
  },
  {
    "id": 44,
    "name": "Smart Tablet",
    "description": "High-quality smart tablet with excellent features and performance",
    "price": 369,
    "category": "Clothing",
    "image": "https://images.unsplash.com/photo-732929916172?w=300&h=300&fit=crop",
    "stock": 28,
    "rating": 4.6,
    "reviews": 90
  },
  {
    "id": 45,
    "name": "Premium Monitor",
    "description": "High-quality premium monitor with excellent features and performance",
    "price": 137,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-720804576860?w=300&h=300&fit=crop",
    "stock": 44,
    "rating": 3.4,
    "reviews": 456
  },
  {
    "id": 46,
    "name": "Durable Tablet",
    "description": "High-quality durable tablet with excellent features and performance",
    "price": 302,
    "category": "Clothing",
    "image": "https://images.unsplash.com/photo-230119998894?w=300&h=300&fit=crop",
    "stock": 12,
    "rating": 3.2,
    "reviews": 456
  },
  {
    "id": 47,
    "name": "Portable Mouse",
    "description": "High-quality portable mouse with excellent features and performance",
    "price": 367,
    "category": "Clothing",
    "image": "https://images.unsplash.com/photo-891427226832?w=300&h=300&fit=crop",
    "stock": 33,
    "rating": 3.7,
    "reviews": 252
  },
  {
    "id": 48,
    "name": "Compact Phone",
    "description": "High-quality compact phone with excellent features and performance",
    "price": 473,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-811329151279?w=300&h=300&fit=crop",
    "stock": 18,
    "rating": 4.6,
    "reviews": 118
  },
  {
    "id": 49,
    "name": "Durable Keyboard",
    "description": "High-quality durable keyboard with excellent features and performance",
    "price": 123,
    "category": "Office",
    "image": "https://images.unsplash.com/photo-367565652307?w=300&h=300&fit=crop",
    "stock": 39,
    "rating": 4.6,
    "reviews": 423
  },
  {
    "id": 50,
    "name": "Advanced Keyboard",
    "description": "High-quality advanced keyboard with excellent features and performance",
    "price": 163,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-928520526476?w=300&h=300&fit=crop",
    "stock": 49,
    "rating": 4.2,
    "reviews": 209
  },
  {
    "id": 51,
    "name": "Wireless Bag",
    "description": "High-quality wireless bag with excellent features and performance",
    "price": 159,
    "category": "Office",
    "image": "https://images.unsplash.com/photo-963716135508?w=300&h=300&fit=crop",
    "stock": 32,
    "rating": 3.7,
    "reviews": 317
  },
  {
    "id": 52,
    "name": "Wireless Monitor",
    "description": "High-quality wireless monitor with excellent features and performance",
    "price": 440,
    "category": "Clothing",
    "image": "https://images.unsplash.com/photo-606466594149?w=300&h=300&fit=crop",
    "stock": 3,
    "rating": 3.2,
    "reviews": 115
  },
  {
    "id": 53,
    "name": "Portable Speaker",
    "description": "High-quality portable speaker with excellent features and performance",
    "price": 205,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-72989865117?w=300&h=300&fit=crop",
    "stock": 38,
    "rating": 3.8,
    "reviews": 172
  },
  {
    "id": 54,
    "name": "High-Quality Chair",
    "description": "High-quality high-quality chair with excellent features and performance",
    "price": 178,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-559459327877?w=300&h=300&fit=crop",
    "stock": 8,
    "rating": 4.7,
    "reviews": 11
  },
  {
    "id": 55,
    "name": "Portable Cable",
    "description": "High-quality portable cable with excellent features and performance",
    "price": 89,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-766470549535?w=300&h=300&fit=crop",
    "stock": 25,
    "rating": 3.2,
    "reviews": 312
  },
  {
    "id": 56,
    "name": "Smart Monitor",
    "description": "High-quality smart monitor with excellent features and performance",
    "price": 395,
    "category": "Sports",
    "image": "https://images.unsplash.com/photo-315652612492?w=300&h=300&fit=crop",
    "stock": 40,
    "rating": 3,
    "reviews": 424
  },
  {
    "id": 57,
    "name": "High-Quality Printer",
    "description": "High-quality high-quality printer with excellent features and performance",
    "price": 421,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-759369129739?w=300&h=300&fit=crop",
    "stock": 31,
    "rating": 3.9,
    "reviews": 357
  },
  {
    "id": 58,
    "name": "Ergonomic Phone",
    "description": "High-quality ergonomic phone with excellent features and performance",
    "price": 265,
    "category": "Clothing",
    "image": "https://images.unsplash.com/photo-131947809191?w=300&h=300&fit=crop",
    "stock": 18,
    "rating": 4.7,
    "reviews": 107
  },
  {
    "id": 59,
    "name": "Compact Keyboard",
    "description": "High-quality compact keyboard with excellent features and performance",
    "price": 166,
    "category": "Books",
    "image": "https://images.unsplash.com/photo-819120554830?w=300&h=300&fit=crop",
    "stock": 39,
    "rating": 3.8,
    "reviews": 15
  },
  {
    "id": 60,
    "name": "Advanced Light",
    "description": "High-quality advanced light with excellent features and performance",
    "price": 422,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-821929826419?w=300&h=300&fit=crop",
    "stock": 1,
    "rating": 3.5,
    "reviews": 358
  },
  {
    "id": 61,
    "name": "Compact Monitor",
    "description": "High-quality compact monitor with excellent features and performance",
    "price": 126,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-46736717369?w=300&h=300&fit=crop",
    "stock": 50,
    "rating": 3.6,
    "reviews": 384
  },
  {
    "id": 62,
    "name": "Wireless Chair",
    "description": "High-quality wireless chair with excellent features and performance",
    "price": 429,
    "category": "Home",
    "image": "https://images.unsplash.com/photo-506301191483?w=300&h=300&fit=crop",
    "stock": 28,
    "rating": 3.2,
    "reviews": 240
  },
  {
    "id": 63,
    "name": "Wireless Tablet",
    "description": "High-quality wireless tablet with excellent features and performance",
    "price": 350,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-343181702843?w=300&h=300&fit=crop",
    "stock": 25,
    "rating": 4.3,
    "reviews": 445
  },
  {
    "id": 64,
    "name": "Professional Glasses",
    "description": "High-quality professional glasses with excellent features and performance",
    "price": 354,
    "category": "Sports",
    "image": "https://images.unsplash.com/photo-990809178787?w=300&h=300&fit=crop",
    "stock": 49,
    "rating": 3.8,
    "reviews": 171
  },
  {
    "id": 65,
    "name": "Professional Glasses",
    "description": "High-quality professional glasses with excellent features and performance",
    "price": 283,
    "category": "Beauty",
    "image": "https://images.unsplash.com/photo-293509864271?w=300&h=300&fit=crop",
    "stock": 47,
    "rating": 3.8,
    "reviews": 382
  },
  {
    "id": 66,
    "name": "Smart Mouse",
    "description": "High-quality smart mouse with excellent features and performance",
    "price": 210,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-714822635079?w=300&h=300&fit=crop",
    "stock": 17,
    "rating": 4.7,
    "reviews": 373
  },
  {
    "id": 67,
    "name": "Advanced Phone",
    "description": "High-quality advanced phone with excellent features and performance",
    "price": 334,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-834128294057?w=300&h=300&fit=crop",
    "stock": 35,
    "rating": 3.7,
    "reviews": 202
  },
  {
    "id": 68,
    "name": "Ergonomic Glasses",
    "description": "High-quality ergonomic glasses with excellent features and performance",
    "price": 273,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-482861617871?w=300&h=300&fit=crop",
    "stock": 50,
    "rating": 4.5,
    "reviews": 66
  },
  {
    "id": 69,
    "name": "Wireless Charger",
    "description": "High-quality wireless charger with excellent features and performance",
    "price": 75,
    "category": "Office",
    "image": "https://images.unsplash.com/photo-645137528318?w=300&h=300&fit=crop",
    "stock": 5,
    "rating": 3.6,
    "reviews": 20
  },
  {
    "id": 70,
    "name": "Advanced Laptop",
    "description": "High-quality advanced laptop with excellent features and performance",
    "price": 377,
    "category": "Books",
    "image": "https://images.unsplash.com/photo-269070306714?w=300&h=300&fit=crop",
    "stock": 28,
    "rating": 3.9,
    "reviews": 115
  },
  {
    "id": 71,
    "name": "Advanced Laptop",
    "description": "High-quality advanced laptop with excellent features and performance",
    "price": 101,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-209238547862?w=300&h=300&fit=crop",
    "stock": 37,
    "rating": 5,
    "reviews": 439
  },
  {
    "id": 72,
    "name": "Smart Mouse",
    "description": "High-quality smart mouse with excellent features and performance",
    "price": 131,
    "category": "Clothing",
    "image": "https://images.unsplash.com/photo-239733554918?w=300&h=300&fit=crop",
    "stock": 35,
    "rating": 3.6,
    "reviews": 408
  },
  {
    "id": 73,
    "name": "Premium Tablet",
    "description": "High-quality premium tablet with excellent features and performance",
    "price": 199,
    "category": "Home",
    "image": "https://images.unsplash.com/photo-868609885836?w=300&h=300&fit=crop",
    "stock": 33,
    "rating": 3,
    "reviews": 112
  },
  {
    "id": 74,
    "name": "High-Quality Mouse",
    "description": "High-quality high-quality mouse with excellent features and performance",
    "price": 293,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-37620747530?w=300&h=300&fit=crop",
    "stock": 34,
    "rating": 3.9,
    "reviews": 216
  },
  {
    "id": 75,
    "name": "Ergonomic Monitor",
    "description": "High-quality ergonomic monitor with excellent features and performance",
    "price": 76,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-77143694971?w=300&h=300&fit=crop",
    "stock": 43,
    "rating": 3.7,
    "reviews": 386
  },
  {
    "id": 76,
    "name": "Professional Laptop",
    "description": "High-quality professional laptop with excellent features and performance",
    "price": 169,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-997368043618?w=300&h=300&fit=crop",
    "stock": 45,
    "rating": 4.5,
    "reviews": 480
  },
  {
    "id": 77,
    "name": "Professional Shoes",
    "description": "High-quality professional shoes with excellent features and performance",
    "price": 154,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-659076325683?w=300&h=300&fit=crop",
    "stock": 30,
    "rating": 3.7,
    "reviews": 253
  },
  {
    "id": 78,
    "name": "Wireless Mouse",
    "description": "High-quality wireless mouse with excellent features and performance",
    "price": 286,
    "category": "Sports",
    "image": "https://images.unsplash.com/photo-291889943033?w=300&h=300&fit=crop",
    "stock": 14,
    "rating": 4,
    "reviews": 133
  },
  {
    "id": 79,
    "name": "Durable Printer",
    "description": "High-quality durable printer with excellent features and performance",
    "price": 427,
    "category": "Home",
    "image": "https://images.unsplash.com/photo-319581854216?w=300&h=300&fit=crop",
    "stock": 17,
    "rating": 4.8,
    "reviews": 113
  },
  {
    "id": 80,
    "name": "Premium Stand",
    "description": "High-quality premium stand with excellent features and performance",
    "price": 230,
    "category": "Home",
    "image": "https://images.unsplash.com/photo-437958054046?w=300&h=300&fit=crop",
    "stock": 20,
    "rating": 4.9,
    "reviews": 72
  },
  {
    "id": 81,
    "name": "Compact Chair",
    "description": "High-quality compact chair with excellent features and performance",
    "price": 12,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-668418963137?w=300&h=300&fit=crop",
    "stock": 44,
    "rating": 4.2,
    "reviews": 404
  },
  {
    "id": 82,
    "name": "Wireless Speaker",
    "description": "High-quality wireless speaker with excellent features and performance",
    "price": 91,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-264440587520?w=300&h=300&fit=crop",
    "stock": 39,
    "rating": 3.3,
    "reviews": 280
  },
  {
    "id": 83,
    "name": "High-Quality Keyboard",
    "description": "High-quality high-quality keyboard with excellent features and performance",
    "price": 395,
    "category": "Books",
    "image": "https://images.unsplash.com/photo-266923800331?w=300&h=300&fit=crop",
    "stock": 48,
    "rating": 3.6,
    "reviews": 458
  },
  {
    "id": 84,
    "name": "Smart Phone",
    "description": "High-quality smart phone with excellent features and performance",
    "price": 297,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-890102433929?w=300&h=300&fit=crop",
    "stock": 43,
    "rating": 3.2,
    "reviews": 96
  },
  {
    "id": 85,
    "name": "High-Quality Watch",
    "description": "High-quality high-quality watch with excellent features and performance",
    "price": 437,
    "category": "Sports",
    "image": "https://images.unsplash.com/photo-353301767045?w=300&h=300&fit=crop",
    "stock": 41,
    "rating": 3.2,
    "reviews": 245
  },
  {
    "id": 86,
    "name": "Premium Charger",
    "description": "High-quality premium charger with excellent features and performance",
    "price": 417,
    "category": "Home",
    "image": "https://images.unsplash.com/photo-408381205738?w=300&h=300&fit=crop",
    "stock": 29,
    "rating": 4.7,
    "reviews": 4
  },
  {
    "id": 87,
    "name": "Ergonomic Headphones",
    "description": "High-quality ergonomic headphones with excellent features and performance",
    "price": 203,
    "category": "Home",
    "image": "https://images.unsplash.com/photo-523697686607?w=300&h=300&fit=crop",
    "stock": 10,
    "rating": 3.6,
    "reviews": 133
  },
  {
    "id": 88,
    "name": "High-Quality Cable",
    "description": "High-quality high-quality cable with excellent features and performance",
    "price": 13,
    "category": "Office",
    "image": "https://images.unsplash.com/photo-459003829807?w=300&h=300&fit=crop",
    "stock": 15,
    "rating": 4.7,
    "reviews": 495
  },
  {
    "id": 89,
    "name": "Wireless Camera",
    "description": "High-quality wireless camera with excellent features and performance",
    "price": 40,
    "category": "Office",
    "image": "https://images.unsplash.com/photo-96696651294?w=300&h=300&fit=crop",
    "stock": 6,
    "rating": 4,
    "reviews": 448
  },
  {
    "id": 90,
    "name": "Portable Monitor",
    "description": "High-quality portable monitor with excellent features and performance",
    "price": 217,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-430143611085?w=300&h=300&fit=crop",
    "stock": 41,
    "rating": 4.4,
    "reviews": 45
  },
  {
    "id": 91,
    "name": "Compact Speaker",
    "description": "High-quality compact speaker with excellent features and performance",
    "price": 274,
    "category": "Sports",
    "image": "https://images.unsplash.com/photo-470021782580?w=300&h=300&fit=crop",
    "stock": 6,
    "rating": 3.4,
    "reviews": 103
  },
  {
    "id": 92,
    "name": "Ergonomic Charger",
    "description": "High-quality ergonomic charger with excellent features and performance",
    "price": 116,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-428570326486?w=300&h=300&fit=crop",
    "stock": 4,
    "rating": 3.3,
    "reviews": 471
  },
  {
    "id": 93,
    "name": "Advanced Headphones",
    "description": "High-quality advanced headphones with excellent features and performance",
    "price": 509,
    "category": "Office",
    "image": "https://images.unsplash.com/photo-599934843145?w=300&h=300&fit=crop",
    "stock": 20,
    "rating": 3.6,
    "reviews": 379
  },
  {
    "id": 94,
    "name": "Compact Charger",
    "description": "High-quality compact charger with excellent features and performance",
    "price": 188,
    "category": "Accessories",
    "image": "https://images.unsplash.com/photo-953525853383?w=300&h=300&fit=crop",
    "stock": 20,
    "rating": 3.1,
    "reviews": 391
  },
  {
    "id": 95,
    "name": "Advanced Keyboard",
    "description": "High-quality advanced keyboard with excellent features and performance",
    "price": 379,
    "category": "Sports",
    "image": "https://images.unsplash.com/photo-368624030769?w=300&h=300&fit=crop",
    "stock": 46,
    "rating": 3.8,
    "reviews": 312
  },
  {
    "id": 96,
    "name": "Portable Tablet",
    "description": "High-quality portable tablet with excellent features and performance",
    "price": 391,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-40014247724?w=300&h=300&fit=crop",
    "stock": 48,
    "rating": 3.5,
    "reviews": 148
  },
  {
    "id": 97,
    "name": "Advanced Light",
    "description": "High-quality advanced light with excellent features and performance",
    "price": 307,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-883349233042?w=300&h=300&fit=crop",
    "stock": 43,
    "rating": 3.6,
    "reviews": 421
  },
  {
    "id": 98,
    "name": "Wireless Keyboard",
    "description": "High-quality wireless keyboard with excellent features and performance",
    "price": 98,
    "category": "Office",
    "image": "https://images.unsplash.com/photo-649194928708?w=300&h=300&fit=crop",
    "stock": 12,
    "rating": 3,
    "reviews": 472
  },
  {
    "id": 99,
    "name": "Premium Monitor",
    "description": "High-quality premium monitor with excellent features and performance",
    "price": 445,
    "category": "Books",
    "image": "https://images.unsplash.com/photo-281853813836?w=300&h=300&fit=crop",
    "stock": 33,
    "rating": 4.7,
    "reviews": 375
  },
  {
    "id": 100,
    "name": "Ergonomic Laptop",
    "description": "High-quality ergonomic laptop with excellent features and performance",
    "price": 193,
    "category": "Books",
    "image": "https://images.unsplash.com/photo-679198062290?w=300&h=300&fit=crop",
    "stock": 41,
    "rating": 3.1,
    "reviews": 387
  },
  {
    "id": 101,
    "name": "Portable Shoes",
    "description": "High-quality portable shoes with excellent features and performance",
    "price": 44,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-501226728206?w=300&h=300&fit=crop",
    "stock": 40,
    "rating": 4.1,
    "reviews": 148
  },
  {
    "id": 102,
    "name": "High-Quality Desk",
    "description": "High-quality high-quality desk with excellent features and performance",
    "price": 362,
    "category": "Office",
    "image": "https://images.unsplash.com/photo-503827267136?w=300&h=300&fit=crop",
    "stock": 29,
    "rating": 3.9,
    "reviews": 486
  },
  {
    "id": 103,
    "name": "Premium Keyboard",
    "description": "High-quality premium keyboard with excellent features and performance",
    "price": 445,
    "category": "Electronics",
    "image": "https://images.unsplash.com/photo-769977577730?w=300&h=300&fit=crop",
    "stock": 19,
    "rating": 3.3,
    "reviews": 343
  },
  {
    "id": 104,
    "name": "Advanced Headphones",
    "description": "High-quality advanced headphones with excellent features and performance",
    "price": 431,
    "category": "Clothing",
    "image": "https://images.unsplash.com/photo-515282582985?w=300&h=300&fit=crop",
    "stock": 11,
    "rating": 3.2,
    "reviews": 157
  },
  {
    "id": 105,
    "name": "Advanced Chair",
    "description": "High-quality advanced chair with excellent features and performance",
    "price": 318,
    "category": "Sports",
    "image": "https://images.unsplash.com/photo-179353134307?w=300&h=300&fit=crop",
    "stock": 33,
    "rating": 4,
    "reviews": 329
  },
  {
    "id": 106,
    "name": "Professional Light",
    "description": "High-quality professional light with excellent features and performance",
    "price": 110,
    "category": "Home",
    "image": "https://images.unsplash.com/photo-603825790248?w=300&h=300&fit=crop",
    "stock": 16,
    "rating": 4,
    "reviews": 227
  },
  {
    "id": 107,
    "name": "Professional Charger",
    "description": "High-quality professional charger with excellent features and performance",
    "price": 118,
    "category": "Sports",
    "image": "https://images.unsplash.com/photo-150983882356?w=300&h=300&fit=crop",
    "stock": 40,
    "rating": 3.6,
    "reviews": 330
  },
  {
    "id": 108,
    "name": "Professional Light",
    "description": "High-quality professional light with excellent features and performance",
    "price": 378,
    "category": "Office",
    "image": "https://images.unsplash.com/photo-487635208181?w=300&h=300&fit=crop",
    "stock": 9,
    "rating": 3.2,
    "reviews": 265
  }
];

export const mockUsers = {
  'admin@example.com': {
    password: 'admin123',
    role: 'admin',
    name: 'Admin User',
  },
  'user@example.com': {
    password: 'user123',
    role: 'user',
    name: 'Test User',
  },
};
